dockerfile

diff --git a/apps/page_router/Dockerfile b/apps/page_router/Dockerfile
--- a/apps/page_router/Dockerfile
+++ b/apps/page_router/Dockerfile
@@ -1,37 +1,67 @@
-FROM node:22.11.0-alpine AS base
+FROM node:18-alpine AS base
 
-RUN  apk add --no-cache libc6-compat && \
-     yarn global add turbo@1.13.4 pnpm@8.9.0
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-FROM base AS builder-app
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-RUN turbo prune page_router --docker
 
-FROM base AS installer-app
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
 
-COPY .gitignore .gitignore
-COPY --from=builder-app /app/out/json/ .
-COPY --from=builder-app /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
-RUN pnpm i
+RUN yarn build
 
-COPY --from=builder-app /app/out/full/ .
-RUN pnpm turbo run build --filter=page_router
+# If using npm comment out above and use below instead
+# RUN npm run build
 
-# Add lockfile and package.json's of isolated subworkspace
+# Production image, copy all the files and run next
 FROM base AS runner
-RUN apk update
 WORKDIR /app
-COPY . .
 
-# First install the dependencies (as they change less often)
-COPY --from=builder /app/out/json/ .
-COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
-RUN yarn global add pnpm@8.9.0 && pnpm i
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
 
-# Build the project and its dependencies
-COPY --from=builder /app/out/full/ .
-#COPY turbo.json turbo.json
-COPY --from=builder turbo.json turbo.json
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
-CMD pnpm turbo dev --filter=page_router
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
+EXPOSE 3000
+
+ENV PORT 3000
+# set hostname to localhost
+ENV HOSTNAME "0.0.0.0"
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+CMD ["node", "server.js"]
